# Generated by Django 2.0.2 on 2022-07-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tipouser',
            field=models.CharField(blank=True, default='Docente', max_length=240, null=True),
        ),
    ]
