# Generated by Django 2.0.2 on 2022-07-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre colaborador')),
                ('correo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo colaborador')),
                ('rut', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rut colaborador')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo colaborador')),
                ('celular', models.IntegerField(blank=True, null=True, verbose_name='Celular colaborador')),
                ('estado', models.CharField(blank=True, default='Activo', max_length=10, null=True, verbose_name='Estado colaborador')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre'],
            },
        ),
    ]
