# Generated by Django 2.0.2 on 2022-07-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proccaa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(blank=True, max_length=100, null=True, verbose_name='Carrera')),
                ('sede', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sede')),
                ('nivel', models.IntegerField(blank=True, null=True, verbose_name='Celular colaborador')),
                ('periodo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Periodo')),
                ('año', models.CharField(blank=True, max_length=100, null=True, verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Formulario de Pago',
                'verbose_name_plural': 'Formularios de Pago',
                'ordering': ['carrera'],
            },
        ),
    ]
