# Generated by Django 2.0.2 on 2022-07-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proccaa', '0002_formpago'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpago',
            name='reunion_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha Reunión 1'),
        ),
        migrations.AddField(
            model_name='formpago',
            name='reunion_1_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='formpago',
            name='reunion_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha Reunión 2'),
        ),
        migrations.AddField(
            model_name='formpago',
            name='reunion_2_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='formpago',
            name='reunion_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha Reunión 3'),
        ),
        migrations.AddField(
            model_name='formpago',
            name='reunion_3_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link'),
        ),
    ]
