# Generated by Django 2.0.2 on 2022-07-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proccaa', '0003_auto_20220724_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpago',
            name='reunion_1_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link 1'),
        ),
        migrations.AlterField(
            model_name='formpago',
            name='reunion_2_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link 2'),
        ),
        migrations.AlterField(
            model_name='formpago',
            name='reunion_3_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Link 3'),
        ),
    ]
