# Generated by Django 2.0.2 on 2022-07-25 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proccaa', '0004_auto_20220724_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodologias', models.CharField(blank=True, max_length=150, null=True, verbose_name='Metodologias')),
                ('capacitaciones', models.CharField(blank=True, max_length=150, null=True, verbose_name='Capacitaciones')),
                ('actividades', models.CharField(blank=True, max_length=150, null=True, verbose_name='Actividades')),
                ('otros', models.CharField(blank=True, max_length=150, null=True, verbose_name='Otros')),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
                ('estrategia', models.TextField(verbose_name='Estrategia')),
                ('respuesta2', models.TextField(verbose_name='Respuesta2')),
                ('respuesta3', models.TextField(verbose_name='Respuesta3')),
                ('respuesta4', models.TextField(verbose_name='Respuesta4')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
                'ordering': ['metodologias'],
            },
        ),
    ]
