# Generated by Django 2.0.2 on 2022-07-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proccaa', '0005_informe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ver_informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Periodo')),
                ('sede', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sede')),
                ('carrera', models.CharField(blank=True, max_length=100, null=True, verbose_name='Carrera')),
                ('nivel', models.IntegerField(blank=True, null=True, verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'VerInforme',
                'verbose_name_plural': 'VerInformes',
                'ordering': ['periodo'],
            },
        ),
    ]
